from shared.exceptions.mapping_not_found_error import MappingNotFoundError
